# range(5,10)
# # 5,6,7,8,9
# range(0,10,3)
# # 0,3,6,9
# range(-10,-100,-30)
# # -10,-40,-70
for i in range(-10,100,30):
    print(i)

print(list(range(5)))#in this list is generated by its own
for n in range(2,10):
    for f in range(2,n):
        if n%f==0:
            print(n,'equal',f,'*',n//f)
            break
    else :
        #loop fell through without finding a factor
        print(n,'is a prime number')
        

while True :
    pass